#!/usr/bin/python -u
# Copyright (c) 2020 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Utilities without connecting to server
"""
from pyclownfish import clownfish_local

if __name__ == "__main__":
    clownfish_local.main()
